keys:
  - &tnmt age124qtmtc34yg8jsre09m6lyf35u4heemwd0jm6609j94ygnrn4p4q7vkg5x
  - &dahlia age1x83l95gqyu5r5d5wjlkfm44q0ggj2tr79njuhgqlqdvlqdgcwvpqmsxgnl

creation_rules:
  - path_regex: secrets/hosts/dahlia\.yaml$
    key_groups:
      - age:
          - *tnmt
          - *dahlia
  - path_regex: secrets/(roles|common).*\.yaml$
    key_groups:
      - age:
          - *tnmt
          - *dahlia
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *tnmt
