[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]

[formatter.shell]
command = "shfmt"
options = ["-w", "-i", "2", "-ci"]
includes = ["*.sh", ".githooks/*", "home-manager/**/scripts/*"]
excludes = ["home-manager/**/scripts/*.nix"]
