#!/usr/bin/env bash

# Launch the default browser. Converts --private into the correct flag.

default_browser=$(xdg-settings get default-web-browser)
browser_exec=""

for profile in \
  "$HOME/.local" \
  "$HOME/.nix-profile" \
  "/etc/profiles/per-user/$USER" \
  /run/current-system/sw \
  /usr; do
  desktop_file="$profile/share/applications/$default_browser"
  if [[ -r "$desktop_file" ]]; then
    browser_exec=$(sed -n 's/^Exec=\([^ ]*\).*/\1/p' "$desktop_file" | head -n 1)
    [[ -n "$browser_exec" ]] && break
  fi
done

if [[ -z $browser_exec ]]; then
  browser_exec="xdg-open"
fi

if $browser_exec --help 2>&1 | grep -q MOZ_LOG; then
  private_flag="--private-window"
elif [[ $browser_exec =~ edge ]]; then
  private_flag="--inprivate"
else
  private_flag="--incognito"
fi

exec setsid "$browser_exec" "${@/--private/$private_flag}"
