git_email: ENC[AES256_GCM,data:3GxLBKA29G0ZQqk=,iv:seOibLZqiSjhqc7FYKuTyG30hehhbvXUETwFAMOvMCQ=,tag:w1vFe5aHGViJlDljIPuokg==,type:str]
git_name: ENC[AES256_GCM,data:mziSxzkIVmGYFZoiIO+Kcao=,iv:RlDREjuq/nBrBs6RpQXcZiwX7tRpWocSNNIcc5HM3TE=,tag:NEbPaoHwlwLFWmpVsNYYjA==,type:str]
lan_prefix: ENC[AES256_GCM,data:Xlp7GqwC51SWJA==,iv:KBAcU8QLZM6btWUxCPYR+EQFzLlb4AKHt4a2hJN0/Rs=,tag:CkTZOR0nxOfDG7dDLcLzng==,type:str]
vps01_host: ENC[AES256_GCM,data:i3V+SkunO/mfgp3CHNaG,iv:6KnP9VTwMKXm0mviVtZhdR6+ZvwofC6HzCtaNkYVk1c=,tag:eZG3eHodvEI6VAuOccMYrQ==,type:str]
sops:
    age:
        - recipient: age124qtmtc34yg8jsre09m6lyf35u4heemwd0jm6609j94ygnrn4p4q7vkg5x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RytId1VIK2tYQUlYVmtv
            RWc4QjZnL1R2SHJEc1I1SW9ESTlNclRPRFg4CkV4QTRoWG5ZOVJ0clRvUEMzZ0FU
            YS9VMFh0anprbVREMno3cTBsNTQ4NWMKLS0tIFBPRE5VN0FZRm5DcExORmtUeVNF
            QkZNYTFmQUUxOWpYajRKb0pSUmlkNWsKylwZsDswx+/xKC2oQazYGRanmizlpXBv
            fDSLTwaPhSR2r7pJOZQ4/yXqcUChhPi2SOP3gjTzzazsWV4tJcE2yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x83l95gqyu5r5d5wjlkfm44q0ggj2tr79njuhgqlqdvlqdgcwvpqmsxgnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcmZHTjF1bHhxeTJRVkxT
            MHNhYXRZdFlJa3NNYUs3OCtVUlFaZy9mRmtrCjV6cTFTcVZHN2paWTV0ZWh3TCtH
            cENWU1B0TW1LTXEwMXMzRGtjNHlvZ2cKLS0tIGZKOTJBbkZGN0VVZTBwQXlFVGJU
            ZVQ5WG5NREhvSk9sWmhxTmx5Um94K0UKirP3cRWGzhKtSBueRwguBVDmz/jf71Cq
            aZ8okiC1cWQhRUURix5qNaZNNJuCWz4BhbAtoKygzyIgEjQU9NJCdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1avnkg4hjnprjsn2f8ehj8nzgzutj930tdx67f9t66gf85k24c3mq0n89jf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ1RMdzZEOFZycFVJMi9K
            QWM3aS9ucWYyaVNuOCt5b3lqdlJkR05idGhzCjNGRmFKeXR3UFBTUERKMTNTdWV0
            dEdFRk4vNTA5cWZxMDRYcnNqTWVvblUKLS0tIGtWZDRhUzc5UTNIQTJjU2hiTUd6
            MW5vSzlOZFF2cS9UdHc2Nkt1cy9mSXcK3nwSiUOk/rHQ0fOojT/GGmBjAHDuOmA6
            XJMxamh+2CyREXBGD8jlu1nCB3JZNGaPFZYSgJfaW8mJu4RU8CsUTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c3w7yxyym205xxuz0slfuh405vn9u69zr5tumenlggcrdjvupaksz424j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeHJLZTBDRzI2WFVRYlBY
            b25hT1lWdUpZMERFYmlkNjU3eEtac2wvSEhZCno1cFVtRWhBU3g4L3hNbmtEc1E1
            eW1Zcm1pQklEWWpYOGkzcXRHQVdMZWsKLS0tIFp2cWFTZUtQRk5paWh1TnhFaUQw
            WlNBdmhGQit0cDhCN2xsd0VQTlZzajAKhmXBBQewsmLcNEZORSa15jOzMZEOaGIA
            Mb2r3CYJwRpg8bFD5wankIH3M0UT8L57uxkIHSJ1hXE7dBFY+e08Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T05:45:06Z"
    mac: ENC[AES256_GCM,data:m4dK7xhE2UIBVQgVZYeZgsd8+FE6P2jl38LHLHVB6ql7yv/ZPj4QiE3PAUHmSVqJITsSHOLcUmRiBarasRYqhCYhb3XxstYOc6dae/zc6gRqe2+27gLcoh+FQOxi4adhK0Z9/6o+GE/aoNKQBqQHzaz6B42Y/Ss19OTRjJGb0Uc=,iv:MUd6XzvBqttgCjESKtve496G48eq06IL4AFQIAqFPTU=,tag:sgjq8xy4MPrXH390Cvog+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
