git_email: ENC[AES256_GCM,data:3GxLBKA29G0ZQqk=,iv:seOibLZqiSjhqc7FYKuTyG30hehhbvXUETwFAMOvMCQ=,tag:w1vFe5aHGViJlDljIPuokg==,type:str]
git_name: ENC[AES256_GCM,data:mziSxzkIVmGYFZoiIO+Kcao=,iv:RlDREjuq/nBrBs6RpQXcZiwX7tRpWocSNNIcc5HM3TE=,tag:NEbPaoHwlwLFWmpVsNYYjA==,type:str]
lan_prefix: ENC[AES256_GCM,data:Xlp7GqwC51SWJA==,iv:KBAcU8QLZM6btWUxCPYR+EQFzLlb4AKHt4a2hJN0/Rs=,tag:CkTZOR0nxOfDG7dDLcLzng==,type:str]
vps01_host: ENC[AES256_GCM,data:i3V+SkunO/mfgp3CHNaG,iv:6KnP9VTwMKXm0mviVtZhdR6+ZvwofC6HzCtaNkYVk1c=,tag:eZG3eHodvEI6VAuOccMYrQ==,type:str]
sops:
    age:
        - recipient: age124qtmtc34yg8jsre09m6lyf35u4heemwd0jm6609j94ygnrn4p4q7vkg5x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybXZYbmdJL1dINHpaVXhQ
            S1ZaS0pEbDRWU0ZuYlVOSW45KzhtaWVmQUg4Cnp2azdlUjN2bWhQcWRqelVJVVY1
            QmhoMy9ZU0txWGZFOFNjSmthWU9PTmcKLS0tIFRFY1FrcmZHZFZ4UzFOa3c3N1hh
            bGJMMjZqY2RrdXV0ZDg5elJKeVh3UE0KXBHyvDEPtV1e8Pon0YGrSPc7m3rFR1y9
            CThC7bjawETvHWcwFi9oVgJLcqAj4UxV2ir/JnsbbqTtR2AdUM3+8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x83l95gqyu5r5d5wjlkfm44q0ggj2tr79njuhgqlqdvlqdgcwvpqmsxgnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT1Z5MG83aUlZdnZmdENX
            SjNlSjRTekIvRnZZUkM5OUlWS1ZBUzJZcm1BCnA1R3V2bW1QcmRwSmVieGNjQ3pj
            WU5wWW15S1ZML0Y2RzNNWGUwak5qWFUKLS0tIGN5T3JRVWpWZ3Y0Tlh0aXloR2t4
            eEFhdERyR1BpVGZtcndTdnRheVMzN0UKz96hm/gIVad2vwqUNYLCyw6KZAgjyFoo
            XH/9ZJEPF5A1b42M6cu4/Y+wTah9hxXz6nAEdYpjMGNXraRX96423g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1avnkg4hjnprjsn2f8ehj8nzgzutj930tdx67f9t66gf85k24c3mq0n89jf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodFh2cUJWSkY2YUdpbGg5
            ZG14eTZpdmlaUEgxTW55LzRMMlFZKzB1djBvCm9hOE94cnBBZU44bXlYc1lPYkRR
            T1FLRm10dEZqWFA5dGE1NktLcTE3VVUKLS0tIG5rYVNIeFo2YW9lTTJRUlhCS0tC
            MDJHc1NHNFhCMU10TllQbGcyTlo4TzQKIrCH7j8li6c1WDThc9ol5W7TvsfwO+OE
            r1K63kfMucWE5XU1U7jnALZ5+Gd+tXn/pgZT4/L7HRm9ms6yDvZiRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T05:45:06Z"
    mac: ENC[AES256_GCM,data:m4dK7xhE2UIBVQgVZYeZgsd8+FE6P2jl38LHLHVB6ql7yv/ZPj4QiE3PAUHmSVqJITsSHOLcUmRiBarasRYqhCYhb3XxstYOc6dae/zc6gRqe2+27gLcoh+FQOxi4adhK0Z9/6o+GE/aoNKQBqQHzaz6B42Y/Ss19OTRjJGb0Uc=,iv:MUd6XzvBqttgCjESKtve496G48eq06IL4AFQIAqFPTU=,tag:sgjq8xy4MPrXH390Cvog+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
