git_email: ENC[AES256_GCM,data:3GxLBKA29G0ZQqk=,iv:seOibLZqiSjhqc7FYKuTyG30hehhbvXUETwFAMOvMCQ=,tag:w1vFe5aHGViJlDljIPuokg==,type:str]
git_name: ENC[AES256_GCM,data:mziSxzkIVmGYFZoiIO+Kcao=,iv:RlDREjuq/nBrBs6RpQXcZiwX7tRpWocSNNIcc5HM3TE=,tag:NEbPaoHwlwLFWmpVsNYYjA==,type:str]
lan_prefix: ENC[AES256_GCM,data:Xlp7GqwC51SWJA==,iv:KBAcU8QLZM6btWUxCPYR+EQFzLlb4AKHt4a2hJN0/Rs=,tag:CkTZOR0nxOfDG7dDLcLzng==,type:str]
vps01_host: ENC[AES256_GCM,data:i3V+SkunO/mfgp3CHNaG,iv:6KnP9VTwMKXm0mviVtZhdR6+ZvwofC6HzCtaNkYVk1c=,tag:eZG3eHodvEI6VAuOccMYrQ==,type:str]
sops:
    age:
        - recipient: age124qtmtc34yg8jsre09m6lyf35u4heemwd0jm6609j94ygnrn4p4q7vkg5x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WldWRmJSZWl2Wnl5eVNM
            dXBIRTExSTEwenkyQTFyV0xsZ1p2WDNmREFNCnM3RHFWK2NHbDhmZVJ1ZndUMU1i
            VnpDUkFHa2dHSEZlazd0SjVXYnloSDQKLS0tIC9NdDRxNmw1VUczdnQyOGtUVkw5
            ZHpienFUZDNubHFWVWwrMG5NanlVeHcK3sgMwgQnQLB0jEqOR0FdF4AxEixQGB4F
            r1RlpbTcNse3Cheei43DzLQYTGI3g01EabKR/TNRj+JWNzkFYAnQ2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x83l95gqyu5r5d5wjlkfm44q0ggj2tr79njuhgqlqdvlqdgcwvpqmsxgnl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z0VlYlE4b2RoeWx4NDR4
            L3FadTlDTnN3cHFQMU42bFRwUUowanRCRFFZCmNYNHBzM0pQckV1bGEvbExaeWlE
            c0ZKaWpvRkd6anFLTHdFM0dIeURzOHcKLS0tIE1ZWTE5SmduTk54SEpJeHZBOEg4
            K05HYW1rRHVYdEs5cWpMeVJVblJvOVUK1tiLud2KlpxKZLzd1+wUvRlMWQbGu9EC
            9qhcBLlVY/7gTdGowx5KP2aNYKOiL4MEgBzuA3iyll77X2tdo3BfzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1avnkg4hjnprjsn2f8ehj8nzgzutj930tdx67f9t66gf85k24c3mq0n89jf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cHJaNTZPK0tNSnhocW1o
            TmJZNDJxOHdtbWVMcDdYOVJyWlBoRU0yZ3ljCkZib09IaFR2OWNpcW1OOXJETW94
            MGFJdFFLNDVSVlRUOE9pRC9tUnFSNFEKLS0tIHdXUjhWR1NYU2VxdzlaVHJEdVBY
            elZTd2FYSTVkZjhRSEhlLzFRL2xINUkKkThRtcLQh/iD923xgNvqfo93hh7YXYxw
            NyyjPN8QrkLUBRBg3FFn0xUfGCUXq5MffXYv+JPmB0nT2DP2xALQzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c3w7yxyym205xxuz0slfuh405vn9u69zr5tumenlggcrdjvupaksz424j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cmQyZ2dBeXB5ZDBicllZ
            SytOOVAraFFPdzRkZDFjVUdJbFVXdnNPVUM0CjhRUENVb1lRTTczb2ppcVc3NVBK
            eXFHUi9ISVRBQmEvVEtBbmpWL2YvWlUKLS0tIGcvbXBNODU5cHVhcXhkOXZUcWk5
            cy9ZcXJjempTWDNNdVV2NHlUaWI2eDAKCt+CecVpRpWai2Fj/teT6vrp/c7Wj/rP
            2xNz9nn5VR/+Kbi5ozuWnAXERYusMapNPyH28ryxtETY1oO8saS+Qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10huk33p52heg6rwltktc9ews6enjaluvqe9lly3pwgehz6jqhf8swkvtq3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UUsxYk12MFIxcVI4U2dk
            NVVpOWs1Z25YQzY1NDhmaytmNXo4STJzQTMwCllBaEgvUVpzdnNnYVQxVktiOVZl
            K2czMWJZRUtmcFFTeEVtVDEzOFJtelUKLS0tIHkxMGhWbGJYczVxWG92WjVMRnA2
            SUtYQUpzRVZnbUxsLzVrRHMrOEFiR0EKM8BymjYBJzvQPgptF0aQozQb/zEOzVYR
            H9PZMl+VjRB54m7vhQ4+aQhelc+DaKUJh3LO8lSp6CCW5mS+vbW34w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t73ldrule2ccx63a2hz229ea54tlgc664gqzhm8tq24zr4ur63usp7ekqd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNjAvSU9OcytMaitqV0E2
            ODBEZlNMKzlxWUJRVk1QK3VtZEJqRVNrTVU0CjlmbjFSYWZlVEZiK3dDLyswWDVu
            TzlSQlR2WUxGTEFKanlIcWhobzk1cWMKLS0tIE91VnpTYVV3Z3EydDdqclhrNXd6
            M1Z1bkRvNFVXUThESitqWmo1VlEvYmcKE7Y4LyBzmdlUV/NxCRBxx/8f1sMJ/AtB
            hU+s7P0MgYOKW+SEEkbyMKcb6Sy5vDnwKAzsVvoB3JVNnifSx1ByTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T05:45:06Z"
    mac: ENC[AES256_GCM,data:m4dK7xhE2UIBVQgVZYeZgsd8+FE6P2jl38LHLHVB6ql7yv/ZPj4QiE3PAUHmSVqJITsSHOLcUmRiBarasRYqhCYhb3XxstYOc6dae/zc6gRqe2+27gLcoh+FQOxi4adhK0Z9/6o+GE/aoNKQBqQHzaz6B42Y/Ss19OTRjJGb0Uc=,iv:MUd6XzvBqttgCjESKtve496G48eq06IL4AFQIAqFPTU=,tag:sgjq8xy4MPrXH390Cvog+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
