git_email: ENC[AES256_GCM,data:GHiANKysC2MoBlRFoKfI3nXOyNXG,iv:5B16I/stFh0V+sybsm6pDYWwSrthl0xxKabUWS3QTQk=,tag:S4oUsXfoslP7o2Uq77CzNQ==,type:str]
git_name: ENC[AES256_GCM,data:VjM0Hk8FLygRkwavCwFtYcY=,iv:pH1yddMN+X617k30Drwkbc0nlsD+4CzF+MBonVRd7Y4=,tag:YxjUFXPW+HoIVByhIktp/g==,type:str]
sops:
    age:
        - recipient: age124qtmtc34yg8jsre09m6lyf35u4heemwd0jm6609j94ygnrn4p4q7vkg5x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZFUreklETDJYYU5jZ3NU
            TGYzTDQxNHNTUFRBVXFWamJiK3MvVjJ1c2w0CnAyeWxDZDBLTEpYdXRoSzhsemNM
            WlNqem5KOFRRQmppNUpGU0dOd29ieEUKLS0tIEVYaEdMMTRkS0YrZnBuZGNSNlUx
            Vys3WnVJU2RvK2VkNWlMMCtBZVdsY3MKK8LQh98T4yO6r1e2jhDJZicU9xfeCAYk
            tN1vNzm6OiIJRkiPje+y55XCi8WdrApfszuKWo1PnzYvltI5tpziFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10huk33p52heg6rwltktc9ews6enjaluvqe9lly3pwgehz6jqhf8swkvtq3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dE1tei84cHB1WGMwSkZZ
            MksxdDErcDZ4MmMwSDFCQ2kvRlFRV2VoSnh3CmtBUURXdmJXS3J1SGk0RERtMTdr
            SHBDd3o0OUZ5b3hGRklYU2o4b0VwcjAKLS0tIG5ic3hLU2N4bGdTcGUrRFU5Q3I1
            TFFTM1I4SnNJOSsxU2JRU2dMVHJ6Z2sKgtTNZXhkhGxxKtclOYdnWtfil6inslUj
            o48NsT2FlI82g/T920IxkLiFRKNHfxIx1lRRWJ8UXnsMhDeVWoSd3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t73ldrule2ccx63a2hz229ea54tlgc664gqzhm8tq24zr4ur63usp7ekqd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcjkvR21yYmxsMmxxbUp4
            OWlVcVdEcjlhQjhVZERFQ1FMTEdRRUVFbEdjCmJ1VSt1TTJPdHUxdnJzdDg5cFJN
            WUNPTitTOXpwTFNicEQvT3l3a0hNQTQKLS0tIHBka2lVZzVFVTFiWHl5RU5iUXdT
            UTBLemd5R0l6OWhrc0ZNUERpSk5tM1UKE5kE/b/o0LT3zVSOTWwWiar4V3N0fCwL
            6ukJNJ6/vvw0Mm60xuyibyJ3+z2fhbXFZXkkXL5nwIuS3OC+RtxnMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T18:43:25Z"
    mac: ENC[AES256_GCM,data:kMgES9bLN5ou3OdRMhbno51IqIQcblL1z4WcbQOu1VyiJVhHr20z4vi5wRHCNjio8CZ5ZQaomd4R902gyeNkugxuSmvtg6Z2DFtPpKjZ5rgrsiP8rmwuYligsMBNjL+/lVGl4KdPx1uD0hNVyhLx/Ljuzh6GFzkN0Bc5pfvnUCE=,iv:PoySLTFBXzWzTgRsIPQTkF9zl/tznIbSxCEVrRqKrk8=,tag:bEuaf9MPS346zB49g/zEQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
