{ inputs, ... }:
{
  imports = [ inputs.hyprdynamicmonitors.homeManagerModules.default ];

  # Hyprland 0.55+ uses Lua, so the generated monitor config must be Lua too.
  # hyprdynamicmonitors is format-agnostic (it just symlinks the static file to
  # `destination` and runs `post_apply_exec`), so the profiles emit `hl.monitor`
  # Lua and the destination is a `.lua` that hyprland.lua dofile()s on reload.
  home.hyprdynamicmonitors = {
    enable = true;
    systemdTarget = "graphical-session.target";
    extraFlags = [ "--disable-power-events" ];
    config = ''
      [general]
      destination = "$HOME/.config/hypr/99_autogenerated-monitors.lua"
      post_apply_exec = "hyprctl reload"

      [profiles.laptop_only]
      config_file = "hyprconfigs/laptop_only.lua"
      config_file_type = "static"

      [[profiles.laptop_only.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "Laptop"

      [profiles.external]
      config_file = "hyprconfigs/external.lua"
      config_file_type = "static"

      [[profiles.external.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "Laptop"

      [[profiles.external.conditions.required_monitors]]
      description = "Dell Inc. DELL U2723QE B9G42P3"
      monitor_tag = "External"

      [fallback_profile]
      config_file = "hyprconfigs/fallback.lua"
      config_file_type = "static"
    '';
  };

  xdg.configFile = {
    "hyprdynamicmonitors/hyprconfigs/laptop_only.lua".text = ''
      hl.monitor({ output = "eDP-1", mode = "1920x1080@60", position = "0x0", scale = 1 })
    '';

    "hyprdynamicmonitors/hyprconfigs/external.lua".text = ''
      hl.monitor({ output = "eDP-1", disabled = true })
      hl.monitor({ output = "DP-1", mode = "3840x2160@60", position = "0x0", scale = 1.25 })
    '';

    "hyprdynamicmonitors/hyprconfigs/fallback.lua".text = ''
      hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
    '';
  };
}
