{ inputs, ... }:
{
  imports = [ inputs.hyprdynamicmonitors.homeManagerModules.default ];

  home.hyprdynamicmonitors = {
    enable = true;
    systemdTarget = "graphical-session.target";
    extraFlags = [ "--disable-power-events" ];
    config = ''
      [general]
      destination = "$HOME/.config/hypr/99_autogenerated-monitors.conf"
      post_apply_exec = "hyprctl reload"

      [profiles.laptop_only]
      config_file = "hyprconfigs/laptop_only.conf"
      config_file_type = "static"

      [[profiles.laptop_only.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "Laptop"

      [profiles.external]
      config_file = "hyprconfigs/external.conf"
      config_file_type = "static"

      [[profiles.external.conditions.required_monitors]]
      name = "eDP-1"
      monitor_tag = "Laptop"

      [[profiles.external.conditions.required_monitors]]
      description = "Dell Inc. DELL U2723QE B9G42P3"
      monitor_tag = "External"

      [fallback_profile]
      config_file = "hyprconfigs/fallback.conf"
      config_file_type = "static"
    '';
  };

  xdg.configFile = {
    "hyprdynamicmonitors/hyprconfigs/laptop_only.conf".text = ''
      monitor = eDP-1, 1920x1080@60, 0x0, 1.0
    '';

    "hyprdynamicmonitors/hyprconfigs/external.conf".text = ''
      monitor = eDP-1, disable
      monitor = DP-1, 3840x2160@60, 0x0, 1.25
    '';

    "hyprdynamicmonitors/hyprconfigs/fallback.conf".text = ''
      monitor = , preferred, auto, auto
    '';
  };
}
