{
  lib,
  terminal,
  theme,
  ...
}:
let
  # Hyprland wants bare RRGGBB hex inside rgba(...)
  hex = color: lib.removePrefix "#" color;
in
{
  # Hyprland 0.55+ uses Lua for its config. Written as raw Lua via extraConfig so
  # ordering (curves before animations, etc.) and the exact output stay under our
  # control instead of the home-manager attrset transpiler's alphabetical ordering.
  wayland.windowManager.hyprland.extraConfig = lib.mkOrder 100 ''
    -- Environment variables
    hl.env("GDK_BACKEND", "wayland,x11,*")
    hl.env("QT_QPA_PLATFORM", "wayland;xcb")
    hl.env("QT_QPA_PLATFORMTHEME", "kvantum")
    hl.env("QT_STYLE_OVERRIDE", "kvantum")
    hl.env("SDL_VIDEODRIVER", "wayland,x11")
    hl.env("MOZ_ENABLE_WAYLAND", "1")
    hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
    hl.env("NIXOS_OZONE_WL", "1")
    hl.env("XMODIFIERS", "@im=fcitx")
    hl.env("INPUT_METHOD", "fcitx")
    hl.env("LANG", "ja_JP.UTF-8")
    hl.env("SSH_AUTH_SOCK", os.getenv("HOME") .. "/.1password/agent.sock")
    hl.env("TERMINAL", "${terminal.default}")

    -- Monitors are managed dynamically by hyprdynamicmonitors, which writes a Lua
    -- file and runs `hyprctl reload`. dofile (not require) re-reads it on every
    -- reload; pcall keeps a first-boot absence from killing the config.
    local cfg_home = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
    pcall(dofile, cfg_home .. "/hypr/99_autogenerated-monitors.lua")

    hl.config({
      general = {
        gaps_in = 3,
        gaps_out = 6,
        border_size = 1,
        col = {
          active_border = { colors = { "rgba(${hex theme.accent}ee)", "rgba(${hex theme.color5}ee)" }, angle = 45 },
          inactive_border = "rgba(${hex theme.bg_highlight}80)",
        },
        resize_on_border = true,
        allow_tearing = true,
        layout = "dwindle",
      },

      decoration = {
        rounding = 8,
        rounding_power = 2,
        inactive_opacity = 0.9,
        shadow = {
          enabled = true,
          range = 1,
          render_power = 3,
          color = "rgba(1a1a1aee)",
        },
        blur = {
          enabled = true,
          size = 8,
          passes = 4,
          special = true,
          noise = 0.034,
          brightness = 1.50,
          contrast = 0.74,
          vibrancy = 1,
          vibrancy_darkness = 0.28,
          xray = true,
        },
      },

      input = {
        kb_layout = "us",
        kb_options = "ctrl:nocaps",
        follow_mouse = 1,
        sensitivity = 0,
        natural_scroll = true,
        touchpad = {
          natural_scroll = true,
        },
      },

      dwindle = {
        preserve_split = true,
        force_split = 2,
      },

      master = {
        new_status = "master",
      },

      misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        focus_on_activate = true,
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
      },

      ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
      },

      cursor = {
        hide_on_key_press = true,
        inactive_timeout = 3,
        warp_on_change_workspace = 1,
      },

      xwayland = {
        force_zero_scaling = true,
      },

      animations = {
        enabled = true,
      },
    })

    -- Bezier curves (defined before animations that reference them)
    hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
    hl.curve("md3_standard", { type = "bezier", points = { { 0.2, 0 }, { 0, 1 } } })
    hl.curve("md3_decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
    hl.curve("md3_accel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
    hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })
    hl.curve("menu_decel", { type = "bezier", points = { { 0.1, 1 }, { 0, 1 } } })
    hl.curve("menu_accel", { type = "bezier", points = { { 0.38, 0.04 }, { 1, 0.07 } } })

    -- Animations
    hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "md3_decel", style = "popin 60%" })
    hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "md3_decel", style = "popin 60%" })
    hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "md3_accel", style = "popin 60%" })
    hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
    hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "md3_decel" })
    hl.animation({ leaf = "layersIn", enabled = true, speed = 3, bezier = "menu_decel", style = "slide" })
    hl.animation({ leaf = "layersOut", enabled = true, speed = 1.6, bezier = "menu_accel" })
    hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 2, bezier = "menu_decel" })
    hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 4.5, bezier = "menu_accel" })
    hl.animation({ leaf = "workspaces", enabled = true, speed = 7, bezier = "menu_decel", style = "slide" })
    hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3, bezier = "md3_decel", style = "slidevert" })

    -- Layer rules
    hl.layer_rule({ match = { namespace = "walker" }, blur = true })
    hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
    hl.layer_rule({ match = { namespace = "notifications" }, blur = true })

    -- Window rules
    hl.window_rule({ match = { class = ".*" }, suppress_event = "maximize" })
    hl.window_rule({ match = { class = ".*" }, opacity = "0.97" })
    -- Float + center for TUI popup windows
    hl.window_rule({ match = { class = "^(tui-float)$" }, float = true })
    hl.window_rule({ match = { class = "^(tui-float)$" }, center = true })
    hl.window_rule({ match = { class = "^(tui-float)$" }, size = { 875, 600 } })
    hl.window_rule({ match = { class = "^(fcitx)$" }, pseudo = true })
    hl.window_rule({ match = { class = "^(fcitx)$" }, no_blur = true })

    -- Autostart
    hl.on("hyprland.start", function()
      hl.exec_cmd("elephant")
      hl.exec_cmd("walker --gapplication-service")
    end)
  '';
}
