git_email: ENC[AES256_GCM,data:3GxLBKA29G0ZQqk=,iv:seOibLZqiSjhqc7FYKuTyG30hehhbvXUETwFAMOvMCQ=,tag:w1vFe5aHGViJlDljIPuokg==,type:str]
git_name: ENC[AES256_GCM,data:mziSxzkIVmGYFZoiIO+Kcao=,iv:RlDREjuq/nBrBs6RpQXcZiwX7tRpWocSNNIcc5HM3TE=,tag:NEbPaoHwlwLFWmpVsNYYjA==,type:str]
atuin_sync_address: ENC[AES256_GCM,data:G+IRMU+aBnz9tnOj7v3Q14H7mHb6cbM=,iv:Yzvn4JxW7pCz4JhbVzn35SG4ukM17fTsxWDGRDoDg2Y=,tag:aXCka3lPTfkFPekj71VdoQ==,type:str]
sops:
    age:
        - recipient: age124qtmtc34yg8jsre09m6lyf35u4heemwd0jm6609j94ygnrn4p4q7vkg5x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NnB0OE1yUmpweC9DTHEw
            QVVuYm50T1pCSVc0bVBTQTU3d1Ezb3haTndzClp6UmdYaW0zRWZsb1RNY0NVd2c2
            MUFNS0JqMUJOSms3N2kxNnBFaE5EY0UKLS0tIGFGYmxyZGVobFZ4MXIvYng5WkF2
            aU96WHExZlViVk9kQXZQRlhYMGVFR1EKGtPp4On+5GHTHJoNAGJXX7NFK7ReYiDd
            L4vybGU78mzR8om27Vfcx8KYBXQtAq16ZIkQjoFs66VzMMYh3ITOZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T15:11:29Z"
    mac: ENC[AES256_GCM,data:R5tK6fOsc2IQAJa3cKsBr3vc0fEhINkRKoAmnaW1BKoJ/SDvJXwnwTSBYLwt5TwNDOJJTBxY3mmVnd0goN7UQAoadpunTUrcElxY27L/xbHSw5sjB8KbMnRCACMlGaWOifWj6Tw8JF0fU27W4SlB19ESR0pXGGnNl2oBR5z14RM=,iv:+pJfuCBJmYtkoU/dRN3GXrMJ1ZwX1t3AfXxS0VmxbPo=,tag:LE3KD8woXpzsXxRrfjZwhw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
