#### icon
# nf-ple-left_half_circle_thick
# nf-pl-left_hard_divider
# nf-pl-left_hard_divider
# nf-pl-right_hard_divider
# nf-ple-right_half_circle_thick

format = """
[╭─](fg:#888888)\
$os\
[ ](fg:#888888 bg:#363636)\
$directory\
$git_branch\
$git_status\
$git_metrics\
[](fg:#363636)\n\
[╰─](fg:#888888)\
$character\
"""

right_format = """
$cmd_duration
$hostname
$time
"""

[os]
format = "[$symbol]($style)"
style = 'fg:#eeeeee bg:#363636'
disabled = false

[os.symbols]
Macos = "  "  # nf-fa-apple
Ubuntu = "  " # nf-linux-ubuntu
Debian = "  " # nf-linux-debian
NixOS = "  "  # nf-linux-nixos

[directory]
truncation_length = 6
truncation_symbol = ' '                                 # nf-fa-folder_open
truncate_to_repo = false
home_symbol = ' ~'                                      # nf-costum-home
style = 'fg:#129dfe bg:#363636'
read_only = ' 󰌾 '                                        # nf-md-lock
read_only_style = 'fg:#f7768e bg:#363636'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = '  '                                         # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 20
truncation_symbol = '...'
style = 'fg:#52d402 bg:#363636'
format = '[  $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
style = 'fg:#e0af68 bg:#363636'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#9ece6a bg:#363636'
deleted_style = 'fg:#9ece6a bg:#363636'
format = '[+$added/-$deleted]($deleted_style)'
disabled = false

[character]
success_symbol = '[❯](bold #9ece6a)'
error_symbol = '[❯](bold red)'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[   $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[hostname]
ssh_only = false
disabled = false
format = '[  $hostname]($style)'

[time]
disabled = false
style = 'fg:#73daca'
format = '[   $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = '%T'
utc_time_offset = '+9'
